# Use the final app image as the build stage
ARG APP_IMAGE=toota-art:latest
FROM ${APP_IMAGE} as app

# Use a fresh nginx image for the final image
FROM nginx:alpine

# Copy the compiled static assets from the app image's public directory
COPY --from=app /var/www/public /var/www/public

# Copy the nginx configuration file
COPY docker/nginx/production.conf /etc/nginx/conf.d/default.conf
